# Generated by Django 6.1.1 on 2026-09-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_price_alter_listing_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listingamenity',
            constraint=models.UniqueConstraint(fields=('listing', 'amenity'), name='unique_listing_amenity'),
        ),
    ]
