# Generated by Django 6.1.1 on 2026-09-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='aggency_approval',
            new_name='agency_approval',
        ),
    ]
