# Generated by Django 6.1.1 on 2026-09-08 12:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_area_name_case_insensitive'),
        ),
    ]
